/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    posts: Post;
    media: Media;
    'home-panels': HomePanel;
    'contact-messages': ContactMessage;
    orders: Order;
    tickets: Ticket;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-panels': HomePanelsSelect<false> | HomePanelsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'our-story': OurStory;
    'events-page': EventsPage;
    'updates-page': UpdatesPage;
    'gallery-page': GalleryPage;
    'contact-info': ContactInfo;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'our-story': OurStorySelect<false> | OurStorySelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'updates-page': UpdatesPageSelect<false> | UpdatesPageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every NexGen event. Events with a date in the future show under "Upcoming"; once the date passes they move to "Past Events" automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * The event name, e.g. "NexGen Presents: Ember Nights".
   */
  title: string;
  /**
   * One short line shown under the title on cards and the event page.
   */
  tagline?: string | null;
  /**
   * Drag to reorder. The first artist is treated as the headliner.
   */
  artists?:
    | {
        name: string;
        /**
         * Optional, e.g. "Headliner", "Support", "Resident DJ".
         */
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Decides whether this is an upcoming or a past event.
   */
  startsAt: string;
  endsAt?: string | null;
  venue: string;
  city?: string | null;
  /**
   * The full write-up shown on the event page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Displayed on the site. Leave blank for a free event, or if tickets are not on sale yet.
   */
  ticketPrice?: number | null;
  currency?: ('LKR' | 'USD' | 'GBP' | 'EUR') | null;
  /**
   * Optional line shown next to the price, e.g. "Early bird until 30 June" or "At the door only".
   */
  ticketNote?: string | null;
  /**
   * Optional. If you sell tickets through another site, paste the link and the button will point there. On-site checkout is not part of this build.
   */
  externalTicketUrl?: string | null;
  soldOut?: boolean | null;
  /**
   * The main photo, used on event cards and at the top of the event page.
   */
  coverImage?: (number | null) | Media;
  /**
   * Optional wide photo used as the full-width backdrop on the event page. A landscape shot works best.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * The web address for this page. Leave blank and it will be created from the title automatically. Avoid changing it once the page is live, or existing links will break.
   */
  slug?: string | null;
  /**
   * Featured events are pulled out first in the homepage events teaser.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * All photos and videos used anywhere on the site. You can drag in several files at once. Tick "Show on the Gallery page" and choose an event to make a photo appear in the public gallery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A short description of what is in the photo, read aloud by screen readers. Example: "DJ performing to a packed crowd at NexGen Live".
   */
  alt?: string | null;
  /**
   * Optional caption shown under the photo in the gallery lightbox.
   */
  caption?: string | null;
  /**
   * Photographer credit, if one is required.
   */
  credit?: string | null;
  /**
   * Which event this photo is from. Used to group photos on the Gallery page and to fill the photo strip on the event page.
   */
  event?: (number | null) | Event;
  /**
   * Only ticked photos appear in the public Gallery. Leave unticked for photos you only want to use elsewhere, such as an event cover.
   */
  showInGallery?: boolean | null;
  /**
   * Optional. Lower numbers appear first in the gallery. Leave blank to sort by newest.
   */
  galleryOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * News, announcements, collaborations, milestones and live recordings. The category you pick decides which section of the Updates page the post appears under.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * One or two sentences shown on the Updates page and in link previews. If left blank the opening of the post is used.
   */
  excerpt?: string | null;
  /**
   * The full post.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown at the top of the post and on the Updates page card.
   */
  coverImage?: (number | null) | Media;
  /**
   * Optional. Links the post to an event so readers can jump straight to it.
   */
  relatedEvent?: (number | null) | Event;
  /**
   * Optional. For live recordings, paste the YouTube / SoundCloud / Spotify link here and the card gets a "Listen" button.
   */
  externalUrl?: string | null;
  /**
   * The web address for this page. Leave blank and it will be created from the title automatically. Avoid changing it once the page is live, or existing links will break.
   */
  slug?: string | null;
  /**
   * Which Updates section this post belongs to.
   */
  category: 'news' | 'artist-announcement' | 'event-announcement' | 'collaboration' | 'milestone' | 'live-recording';
  /**
   * Controls the date shown on the post and the order posts are listed in.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The scrolling photo panels on the homepage. Each panel is one artist photo on top of one full-width background photo, with a heading. Use the "Order" number to arrange them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-panels".
 */
export interface HomePanel {
  id: number;
  /**
   * Panel 1 shows first. Lower numbers come first.
   */
  order: number;
  /**
   * The large headline on the panel. Keep it to a handful of words — it is set in the big condensed display type.
   */
  heading: string;
  /**
   * Optional smaller line above the heading.
   */
  subheading?: string | null;
  /**
   * The centred foreground photo. Portrait shots work best. This is the photo that scales up as the panel arrives.
   */
  artistImage: number | Media;
  /**
   * The full-width photo behind it, acting as the canvas. A wide landscape crowd or stage shot works best.
   */
  backgroundImage: number | Media;
  /**
   * The colour of the block behind this panel’s heading.
   */
  accent?: ('nexgen-red' | 'ember-red' | 'chrome-grey') | null;
  link?: {
    label?: string | null;
    /**
     * e.g. /events or a full https:// link.
     */
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the Contact Us form. These are also emailed to you — this is the backup copy, so nothing is ever lost.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  handled?: boolean | null;
  /**
   * Unticked means Resend was unavailable — read the message here instead.
   */
  emailDelivered?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Empty by design. On-site ticket sales are not part of this build; this is the table a future checkout would write into.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  event: number | Event;
  email: string;
  buyerName?: string | null;
  quantity: number;
  amountTotal?: number | null;
  currency?: string | null;
  status?: ('pending' | 'paid' | 'refunded' | 'cancelled') | null;
  /**
   * e.g. "stripe". Left blank until a gateway is connected.
   */
  paymentProvider?: string | null;
  /**
   * The provider’s session or payment intent id, for reconciliation.
   */
  paymentReference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Empty by design. One row per admitted person, created by a future checkout flow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  /**
   * The unique code that would be scanned on the door.
   */
  code: string;
  order?: (number | null) | Order;
  event: number | Event;
  holderName?: string | null;
  status?: ('valid' | 'checked-in' | 'void') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log in and edit the website. Invite a colleague by creating an account here and sending them the password you set.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the top-right of the admin panel.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'home-panels';
        value: number | HomePanel;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  artists?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  startsAt?: T;
  endsAt?: T;
  venue?: T;
  city?: T;
  description?: T;
  ticketPrice?: T;
  currency?: T;
  ticketNote?: T;
  externalTicketUrl?: T;
  soldOut?: T;
  coverImage?: T;
  backgroundImage?: T;
  slug?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  relatedEvent?: T;
  externalUrl?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  event?: T;
  showInGallery?: T;
  galleryOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-panels_select".
 */
export interface HomePanelsSelect<T extends boolean = true> {
  order?: T;
  heading?: T;
  subheading?: T;
  artistImage?: T;
  backgroundImage?: T;
  accent?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  handled?: T;
  emailDelivered?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  event?: T;
  email?: T;
  buyerName?: T;
  quantity?: T;
  amountTotal?: T;
  currency?: T;
  status?: T;
  paymentProvider?: T;
  paymentReference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  code?: T;
  order?: T;
  event?: T;
  holderName?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The text and video on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * The full-screen looping video at the top of the page. Upload an MP4 (no sound is played). Leave blank to keep the video that ships with the site.
   */
  heroVideo?: (number | null) | Media;
  /**
   * A still image shown instantly while the video loads, so visitors never see a blank screen. Ideally the video’s first frame.
   */
  heroPoster?: (number | null) | Media;
  /**
   * The main line over the video.
   */
  heroHeadline: string;
  /**
   * One supporting sentence under the headline.
   */
  heroSubheadline?: string | null;
  /**
   * The small prompt at the bottom of the hero telling people to scroll.
   */
  heroScrollHint?: string | null;
  /**
   * Up to two buttons over the video. Drag to reorder.
   */
  heroButtons?:
    | {
        label: string;
        /**
         * e.g. /events
         */
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The small label above the intro line, before the photo panels start.
   */
  panelsEyebrow?: string | null;
  /**
   * The large statement that fills the screen and lights up word by word as you scroll into the panels.
   */
  panelsIntro: string;
  /**
   * The three blocks near the bottom of the homepage that send people into Events, Updates and Gallery.
   */
  teasers?:
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        linkLabel: string;
        linkUrl: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The four sections of the Our Story page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story".
 */
export interface OurStory {
  id: number;
  intro: {
    eyebrow?: string | null;
    heading: string;
    /**
     * The opening paragraph, set larger than the rest.
     */
    standfirst?: string | null;
    /**
     * Wide photo behind the page header.
     */
    image?: (number | null) | Media;
  };
  whatIsNexGen: {
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Optional photo shown alongside this section.
     */
    image?: (number | null) | Media;
    /**
     * Optional short line pulled out in large type — good for a value or a statement of intent.
     */
    pullQuote?: string | null;
  };
  whyWeStarted: {
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Optional photo shown alongside this section.
     */
    image?: (number | null) | Media;
    /**
     * Optional short line pulled out in large type — good for a value or a statement of intent.
     */
    pullQuote?: string | null;
  };
  whatWeStandFor: {
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Optional photo shown alongside this section.
     */
    image?: (number | null) | Media;
    /**
     * Optional short line pulled out in large type — good for a value or a statement of intent.
     */
    pullQuote?: string | null;
  };
  community: {
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Optional photo shown alongside this section.
     */
    image?: (number | null) | Media;
    /**
     * Optional short line pulled out in large type — good for a value or a statement of intent.
     */
    pullQuote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The wording on the Events page. The events themselves are under Content → Events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: number;
  /**
   * The band at the top of the page, over a full-width photograph.
   */
  intro?: {
    /**
     * The small line above the heading.
     */
    eyebrow?: string | null;
    /**
     * The large heading. Keep it short — it is set very big.
     */
    heading?: string | null;
    /**
     * The opening paragraph, set larger than body text. Optional.
     */
    standfirst?: string | null;
    /**
     * Optional. Leave empty and the page uses the next event's own artwork.
     */
    image?: (number | null) | Media;
  };
  upcoming?: {
    heading?: string | null;
    /**
     * The word after the number, as in "3 scheduled". The number is counted automatically.
     */
    countLabel?: string | null;
  };
  /**
   * Shown in place of the list when there are no upcoming events.
   */
  upcomingEmpty?: {
    heading?: string | null;
    body?: string | null;
    /**
     * Optional link shown after the paragraph.
     */
    linkLabel?: string | null;
    /**
     * Where that link goes, for example /contact.
     */
    linkUrl?: string | null;
  };
  /**
   * This section hides itself automatically until there is a past event.
   */
  past?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * The link across from the heading, which opens the Gallery page.
     */
    galleryLinkLabel?: string | null;
  };
  seo?: {
    /**
     * Shown in the browser tab and in search results. The site name is added automatically.
     */
    title?: string | null;
    /**
     * The sentence under the title in search results. Aim for 1–2 lines.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The wording on the Updates page. The posts themselves are under Content → Updates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates-page".
 */
export interface UpdatesPage {
  id: number;
  /**
   * The band at the top of the page, over a full-width photograph.
   */
  intro?: {
    /**
     * The small line above the heading.
     */
    eyebrow?: string | null;
    /**
     * The large heading. Keep it short — it is set very big.
     */
    heading?: string | null;
    /**
     * The opening paragraph, set larger than body text. Optional.
     */
    standfirst?: string | null;
    /**
     * Optional. Leave empty and the page uses the newest post's cover photo.
     */
    image?: (number | null) | Media;
  };
  /**
   * The category buttons themselves come from the categories on each post, so they always match.
   */
  filters?: {
    /**
     * The first button, which clears the filter.
     */
    allLabel?: string | null;
  };
  /**
   * Shown when no posts have been published yet.
   */
  empty?: {
    heading?: string | null;
    body?: string | null;
    /**
     * Optional link shown after the paragraph.
     */
    linkLabel?: string | null;
    /**
     * Where that link goes, for example /contact.
     */
    linkUrl?: string | null;
  };
  /**
   * The strip at the foot of the page, under the posts.
   */
  outro?: {
    heading?: string | null;
    body?: string | null;
    /**
     * Optional link shown after the paragraph.
     */
    linkLabel?: string | null;
    /**
     * Where that link goes, for example /contact.
     */
    linkUrl?: string | null;
  };
  seo?: {
    /**
     * Shown in the browser tab and in search results. The site name is added automatically.
     */
    title?: string | null;
    /**
     * The sentence under the title in search results. Aim for 1–2 lines.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The wording on the Gallery page. Which photos appear is set per photo under Content → Images & Videos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  /**
   * The band at the top of the page, over a full-width photograph.
   */
  intro?: {
    /**
     * The small line above the heading.
     */
    eyebrow?: string | null;
    /**
     * The large heading. Keep it short — it is set very big.
     */
    heading?: string | null;
    /**
     * The opening paragraph, set larger than body text. Optional.
     */
    standfirst?: string | null;
    /**
     * Optional. Leave empty and the page uses the first photograph in the gallery.
     */
    image?: (number | null) | Media;
  };
  /**
   * Photos tagged with an event are grouped under that event’s name automatically.
   */
  groups?: {
    /**
     * The heading over photos that have not been tagged with an event. Always shown last.
     */
    untaggedHeading?: string | null;
    /**
     * The link beside each event group, which opens that event’s page.
     */
    eventLinkLabel?: string | null;
  };
  /**
   * Shown when no photographs have been tagged for the gallery yet.
   */
  empty?: {
    heading?: string | null;
    body?: string | null;
    /**
     * Optional link shown after the paragraph.
     */
    linkLabel?: string | null;
    /**
     * Where that link goes, for example /contact.
     */
    linkUrl?: string | null;
  };
  seo?: {
    /**
     * Shown in the browser tab and in search results. The site name is added automatically.
     */
    title?: string | null;
    /**
     * The sentence under the title in search results. Aim for 1–2 lines.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Your contact details, the Contact Us page wording, and the social links used across the whole site including the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  eyebrow?: string | null;
  heading: string;
  /**
   * The line under the heading, above the form.
   */
  standfirst?: string | null;
  /**
   * Shown once someone successfully sends the form.
   */
  formSuccessMessage?: string | null;
  /**
   * Wide photo behind the page header.
   */
  image?: (number | null) | Media;
  /**
   * The public enquiries address shown on the page.
   */
  email?: string | null;
  /**
   * Optional second address for artist and booking enquiries.
   */
  bookingEmail?: string | null;
  phone?: string | null;
  /**
   * Shown as written, so use line breaks how you want them to appear.
   */
  address?: string | null;
  /**
   * Optional, e.g. "Mon–Fri, 9am–6pm".
   */
  openingHours?: string | null;
  /**
   * Shown in the footer, the menu and on the Contact page. Drag to reorder. Delete a row to remove that platform.
   */
  socials?:
    | {
        platform:
          'instagram' | 'tiktok' | 'facebook' | 'youtube' | 'x' | 'spotify' | 'soundcloud' | 'whatsapp' | 'other';
        /**
         * Optional override, e.g. "@nexgen.lk".
         */
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The announcement bar, navigation menu, header button, footer text and the default title/description search engines show.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcement?: {
    enabled?: boolean | null;
    /**
     * The strip across the very top of every page.
     */
    text?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  /**
   * The links in the pop-out menu, in order. Drag to reorder, or delete a row to hide a page from the menu.
   */
  navItems?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional small text shown in the header, to the left of the button — for example the next event and city. Leave empty to show only the NexGen logo. Use " / " to split it across two lines.
   */
  headerTagline?: string | null;
  headerCta?: {
    label?: string | null;
    url?: string | null;
  };
  /**
   * Applies to the whole site at once — every heading, paragraph and button scales together, keeping their relative proportions. There is no need to set sizes element by element.
   */
  typography?: {
    /**
     * "As designed" is the size the site was built and reviewed at. The others step away from it proportionally — nothing will break at any setting, but the extremes are worth previewing before saving.
     */
    textSize?: ('0.85' | '0.9' | '0.95' | '1' | '1.05' | '1.1' | '1.2') | null;
    /**
     * How heavy the condensed display type is. The heaviest matches the weight of the NexGen logo.
     */
    headingWeight?: ('600' | '700' | '800') | null;
  };
  /**
   * A short line about NexGen shown in the footer.
   */
  footerBlurb?: string | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightName?: string | null;
  seo?: {
    /**
     * Shown in the browser tab and in search results.
     */
    defaultTitle?: string | null;
    /**
     * One or two sentences describing NexGen. Around 155 characters.
     */
    defaultDescription?: string | null;
    /**
     * The picture that appears when someone shares a link to the site on social media. 1200×630 works best.
     */
    shareImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroVideo?: T;
  heroPoster?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroScrollHint?: T;
  heroButtons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  panelsEyebrow?: T;
  panelsIntro?: T;
  teasers?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        linkLabel?: T;
        linkUrl?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story_select".
 */
export interface OurStorySelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        standfirst?: T;
        image?: T;
      };
  whatIsNexGen?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        pullQuote?: T;
      };
  whyWeStarted?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        pullQuote?: T;
      };
  whatWeStandFor?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        pullQuote?: T;
      };
  community?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        pullQuote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        standfirst?: T;
        image?: T;
      };
  upcoming?:
    | T
    | {
        heading?: T;
        countLabel?: T;
      };
  upcomingEmpty?:
    | T
    | {
        heading?: T;
        body?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  past?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        galleryLinkLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates-page_select".
 */
export interface UpdatesPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        standfirst?: T;
        image?: T;
      };
  filters?:
    | T
    | {
        allLabel?: T;
      };
  empty?:
    | T
    | {
        heading?: T;
        body?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  outro?:
    | T
    | {
        heading?: T;
        body?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        standfirst?: T;
        image?: T;
      };
  groups?:
    | T
    | {
        untaggedHeading?: T;
        eventLinkLabel?: T;
      };
  empty?:
    | T
    | {
        heading?: T;
        body?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  standfirst?: T;
  formSuccessMessage?: T;
  image?: T;
  email?: T;
  bookingEmail?: T;
  phone?: T;
  address?: T;
  openingHours?: T;
  socials?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  headerTagline?: T;
  headerCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  typography?:
    | T
    | {
        textSize?: T;
        headingWeight?: T;
      };
  footerBlurb?: T;
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightName?: T;
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        shareImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}